# Generated by Django 5.2.7 on 2025-10-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_rename_created_at_post_date_posted_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_url',
            new_name='img_url',
        ),
    ]
