# Generated by Django 5.2.7 on 2025-10-10 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
