# Generated by Django 5.2.7 on 2025-10-11 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Category',
            new_name='category',
        ),
    ]
