# Generated by Django 5.2.7 on 2025-10-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_rename_category_post_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='aboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('avatar_url', models.URLField(blank=True, default='https://placehold.co/100x100/1F2937/FFFFFF?text=A', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
